# Generated by Django 4.2.6 on 2023-12-27 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ko_sentence', models.CharField(max_length=250)),
                ('en_sentence', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='WritingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_sentence', models.CharField(max_length=250)),
                ('score', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educations.sentence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SpeakingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('audio', models.FileField(upload_to='')),
                ('input_script', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
